name: Organize LeetCode

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  organize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: python organize.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add .

          if ! git diff --cached --quiet; then
            git commit -m "Auto organize LeetCode"
            git push
          fi
